# Generated by Django 4.0b1 on 2021-11-17 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_remove_product_images_product_images'),
        ('customer', '0004_remove_cart_user_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(choices=[('Mpamba', 'Mpamba'), ('Airtel Money', 'Airtel Money'), ('National bank', 'National Bank'), ('Kaku Pay', 'Kaku Pay')], max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(related_name='orders', to='products.Product')),
                ('user', models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
