# Generated by Django 4.0b1 on 2021-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a very safe product', max_length=255),
            preserve_default=False,
        ),
    ]
