# Generated by Django 4.0b1 on 2021-11-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_category_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
